version: "3.1"
services:
  node:
   image: img_node14:1.0
   restart: always
   ports:
    - "${REACT_PORT}:3000"
   expose:
    - "${REACT_PORT}"
   volumes:
    - n_data:/app/react-app
    #- /app/react-app/node_modules/
   command: sh -c " cd /app/react-app && npm start && echo \"your port is ${REACT_PORT}\""


volumes:
 n_data:
  driver: local
  driver_opts:
    o: bind
    type: none
    device: "${PATH_VOLUME}"
